//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.01.11 at 04:41:34 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fatea.br/simplebank/soap/payment/v1")
package br.fatea.simplebank.soap.payment.v1;
