//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.22 at 11:21:29 PM BRST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://fatea.br/simplebank/soap/payment")
package br.fatea.simplebank.soap.payment;
